// @ts-nocheck
"use strict";
/*
 * The settings as the firmware reports them in GET /api/params (two axes, wind sensor with
 * direction). Printed by the firmware's own code (src/control/params.cpp, built for the PC),
 * so names, limits and defaults are the real ones.
 */
module.exports = [
    {
        "key": "stormKmh",
        "group": "safety",
        "type": "float",
        "unit": "km/h",
        "value": 40.0,
        "default": 40.0,
        "min": 20.0,
        "max": 60.0,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "stormHoldMs",
        "group": "safety",
        "type": "int",
        "unit": "ms",
        "value": 600000,
        "default": 600000,
        "min": 300000,
        "max": 3600000,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "motorDeadtimeMs",
        "group": "safety",
        "type": "int",
        "unit": "ms",
        "value": 500,
        "default": 500,
        "min": 300,
        "max": 5000,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "motorMaxRunMsElevation",
        "group": "safety",
        "type": "int",
        "unit": "ms",
        "value": 60000,
        "default": 60000,
        "min": 5000,
        "max": 300000,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "motorMaxRunMsAzimuth",
        "group": "safety",
        "type": "int",
        "unit": "ms",
        "value": 90000,
        "default": 90000,
        "min": 5000,
        "max": 300000,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "limitSwitchesElevation",
        "group": "commissioning",
        "type": "bool",
        "unit": "",
        "value": true,
        "default": true,
        "min": null,
        "max": null,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "limitSwitchesAzimuth",
        "group": "commissioning",
        "type": "bool",
        "unit": "",
        "value": true,
        "default": true,
        "min": null,
        "max": null,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "sunChEast",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 0,
        "default": 0,
        "min": 0,
        "max": 3,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "sunChWest",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 1,
        "default": 1,
        "min": 0,
        "max": 3,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "sunChSouth",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 2,
        "default": 2,
        "min": 0,
        "max": 3,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "sunChNorth",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 3,
        "default": 3,
        "min": 0,
        "max": 3,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "sunNorthMeansUp",
        "group": "commissioning",
        "type": "bool",
        "unit": "",
        "value": true,
        "default": true,
        "min": null,
        "max": null,
        "apply": "standstill",
        "pending": null
    },
    {
        "key": "stormParkElevationPlus",
        "group": "commissioning",
        "type": "bool",
        "unit": "",
        "value": true,
        "default": true,
        "min": null,
        "max": null,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windBaud",
        "group": "commissioning",
        "type": "int",
        "unit": "baud",
        "value": 9600,
        "default": 9600,
        "min": 1200,
        "max": 115200,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windSpeedAddr",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 1,
        "default": 1,
        "min": 1,
        "max": 247,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windSpeedFunction",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 3,
        "default": 3,
        "min": 3,
        "max": 4,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windSpeedRegister",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 0,
        "default": 0,
        "min": 0,
        "max": 65535,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windSpeedScale",
        "group": "commissioning",
        "type": "float",
        "unit": "m/s",
        "value": 0.1,
        "default": 0.1,
        "min": 0.001,
        "max": 10.0,
        "apply": "confirm",
        "pending": null
    },
    {
        "key": "windDirAddr",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 1,
        "default": 1,
        "min": 1,
        "max": 247,
        "apply": "now",
        "pending": null
    },
    {
        "key": "windDirFunction",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 3,
        "default": 3,
        "min": 3,
        "max": 4,
        "apply": "now",
        "pending": null
    },
    {
        "key": "windDirRegister",
        "group": "commissioning",
        "type": "int",
        "unit": "",
        "value": 1,
        "default": 1,
        "min": 0,
        "max": 65535,
        "apply": "now",
        "pending": null
    },
    {
        "key": "windDirScale",
        "group": "commissioning",
        "type": "float",
        "unit": "deg",
        "value": 0.1,
        "default": 0.1,
        "min": 0.001,
        "max": 10.0,
        "apply": "now",
        "pending": null
    },
    {
        "key": "trackStartPermille",
        "group": "control",
        "type": "int",
        "unit": "permille",
        "value": 80,
        "default": 80,
        "min": 30,
        "max": 300,
        "apply": "now",
        "pending": null
    },
    {
        "key": "trackStopPermille",
        "group": "control",
        "type": "int",
        "unit": "permille",
        "value": 20,
        "default": 20,
        "min": 5,
        "max": 100,
        "apply": "now",
        "pending": null
    },
    {
        "key": "trackStartDelayMs",
        "group": "control",
        "type": "int",
        "unit": "ms",
        "value": 3000,
        "default": 3000,
        "min": 0,
        "max": 60000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "trackSettleMs",
        "group": "control",
        "type": "int",
        "unit": "ms",
        "value": 15000,
        "default": 15000,
        "min": 0,
        "max": 600000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "trackMaxMoveMs",
        "group": "control",
        "type": "int",
        "unit": "ms",
        "value": 20000,
        "default": 20000,
        "min": 1000,
        "max": 120000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "nightEnterLevel",
        "group": "control",
        "type": "int",
        "unit": "",
        "value": 4000,
        "default": 4000,
        "min": 0,
        "max": 100000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "nightExitLevel",
        "group": "control",
        "type": "int",
        "unit": "",
        "value": 6000,
        "default": 6000,
        "min": 0,
        "max": 130000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "nightDelayMs",
        "group": "control",
        "type": "int",
        "unit": "ms",
        "value": 300000,
        "default": 300000,
        "min": 10000,
        "max": 3600000,
        "apply": "now",
        "pending": null
    },
    {
        "key": "nightReturnEast",
        "group": "control",
        "type": "bool",
        "unit": "",
        "value": true,
        "default": true,
        "min": null,
        "max": null,
        "apply": "now",
        "pending": null
    },
    {
        "key": "logLevel",
        "group": "diagnostics",
        "type": "int",
        "unit": "",
        "value": 4,
        "default": 4,
        "min": 0,
        "max": 5,
        "apply": "now",
        "pending": null
    }
];
